package ca.ciccc.coronarace.entities;

public enum EntityType {
    PLAYER, ENEMY, MEDICINE, BAR, HOME, TREE,
    LEVEL_ONE,LEVEL_TWO,LEVEL_THREE,LEVEL_FOUR,LEVEL_FIVE,LEVEL_SIX,LEVEL_SEVEN,LEVEL_EIGHT,LEVEL_NINE,LEVEL_TEN
}
